<?php require __DIR__ . '/../commom/header.php'; ?>
<div class="page-wrap d-flex flex-row align-items-center">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 text-center">
                <span class="display-1 d-block">405</span>
                <div class="mb-4 lead">Método não permitido.</div>
                <p>Você tentou acessor este endereço por um método não permitido ou não implementado. Contacte o administrador do sistema.</p>
            </div>
        </div>
    </div>
</div>
<?php require __DIR__ . '/../commom/footer.php'; ?>
