{% extends "base.phtml" %}

{% block content %}
{% for key, mensagem in mensagens %}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    <strong>{{ key }}</strong>
    {% for msg in mensagem %}
    {{ msg }}
    {% endfor %}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endfor %}
<div class="container">
    <h2 class="display-4 text-center mb-4">Grupos</h2>
    <div class="row">
        <div class="col">
            <div class="table-responsive">
                <table class="table table-striped table-borderless table-sm">
                    <thead class="thead-dark">
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Nome</th>
                            <th scope="col">Ação</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for grupo in grupos %}
                        <tr>
                            <th scope="row">{{ grupo.id }}</th>
                            <td>{{ grupo.nome }}</td>
                            <td>
                                <a class="btn btn-sm btn-warning" href="{{ url }}grupos/{{ grupo.id }}" role="button">
                                    <i class="fas fa-edit"></i>
                                </a>
                                <button type="button" class="btn btn-sm btn-danger" onclick="deletar({{ grupo.id }})" role="button">
                                    <i class="fas fa-trash-alt"></i>
                                    </a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="col-sm-1"></div>
        <div class="col">
            <form class="row" method="post" action="{{ url }}grupos/{{ grupo.id }}">
                <div class="form-group col-sm-10">
                    <input type="hidden" name="id" value="{{ grupo.id }}" />
                    <label for="nome" class="sr-only">Nome:</label>
                    <input type="text" class="form-control" id="nome_grupo" name="nome" aria-describedby="nomeHelp" placeholder="Nome" value="{{ grupo.nome }}">
                    <small id="nomeHelp" class="form-text text-muted">Nome do grupo.</small>
                </div>
                <div class="form-group col-sm-2">
                    <button type="submit" class="btn btn-primary">Gravar</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}
{% block js %}
<script>
    const deletar = function(id) {
        const swalWithBootstrapButtons = Swal.mixin({
            customClass: {
                confirmButton: 'btn btn-success',
                cancelButton: 'btn btn-danger'
            },
            buttonsStyling: false
        });
        swalWithBootstrapButtons.fire({
            title: 'Apagar?',
            text: "Esta ação irá apagar este registro!",
            type: 'warning',
            showCancelButton: true,
            confirmButtonText: 'Sim, apague!',
            cancelButtonText: 'Não, cancele!',
            reverseButtons: true
        }).then((result) => {
            if (result.value) {
                $.post($('#base_url').val() + 'grupos/' + id + '/del', function(data) {
                    swalWithBootstrapButtons.fire('Apagado!', 'O registro foi apagado.', 'success');
                    location.reload();
                });
            } else if (result.dismiss === Swal.DismissReason.cancel) {
                swalWithBootstrapButtons.fire('Cancelado', 'O registro foi preservado :)', 'error');
            }
        });
    }
</script>
{% endblock %}
