{% extends "base.phtml" %}

{% block css %}
<link href="{{ url }}assets/css/signin.css" rel="stylesheet">
{% endblock %}
{% block menu %} {% endblock %}
{% block content %}

<div class="container-fluid text-center">
    {% for key, mensagem in mensagens %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <strong>{{ key }}</strong>
        {% for msg in mensagem %}
        {{ msg }}
        {% endfor %}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endfor %}
    <form class="form-signin" method="post" action="{{ url }}login">
        <img class="mb-4" src="{{ url }}assets/img/reciclagem.png" alt="" width="72" height="72">
        <h1 class="h3 mb-3 font-weight-normal">Waste Online</h1>
        <label for="usuario" class="sr-only">Usuário</label>
        <input type="text" id="usuario" name="usuario" class="form-control" placeholder="Usuário" required autofocus>
        <label for="senha" class="sr-only">Senha</label>
        <input type="password" id="senha" name="senha" class="form-control" placeholder="Senha" required>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Entrar</button>
        <p class="mt-5 mb-3 text-muted">&copy; 2019</p>
    </form>
    <a href="{{ url }}cliente/login" class="btn btn-link text-center">Acesso do Cliente</a>
</div>

{% endblock %}
