{% extends "base.phtml" %}

{% block content %}

<div class="container">
    <h2 class="display-4 text-center mb-4">Pontuação</h2>
    <div class="row">
        <div class="col">
            <div class="table-responsive">
                <table class="table table-striped table-borderless table-sm">
                    <thead class="thead-dark">
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Grupo</th>
                            <th scope="col">Usuário</th>
                            <th scope="col">Pontuação</th>
                            <th scope="col">Ação</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for ponto in pontuacao %}
                        <tr>
                            <th scope="row">{{ ponto.id }}</th>
                            <td>{{ ponto.grupo }}</td>
                            <td>{{ ponto.usuario }}</td>
                            <td>
                                <span class="badge badge-danger" title="Plástico">{{ ponto.plastico | number_format(2, ',', '') }} kg</span>
                                <span class="badge badge-warning" title="Metal">{{ ponto.metal | number_format(2, ',', '') }} kg</span>
                                <span class="badge badge-primary" title="Papel">{{ ponto.papel | number_format(2, ',', '') }} kg</span>
                                <span class="badge badge-success" title="Vidro">{{ ponto.vidro | number_format(2, ',', '') }} kg</span>
                                <span class="badge badge-dark" title="Óleo">{{ ponto.oleo | number_format(2, ',', '') }} L</span>
                            </td>
                            <td>
                                <a class="btn btn-sm btn-primary insert-id" href="#" role="button" data-toggle="modal"
                                   data-target="#insertPontuacao" data-id="{{ ponto.id }}">
                                    <i class="fas fa-plus-circle"></i>
                                </a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="insertPontuacao" tabindex="-1" role="dialog" aria-labelledby="insertPontuacaoLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <form method="post" action="{{ url }}pontuacao/">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <input type="hidden" name="id" id="id_pontuacao" value="" />
                    <div class="form-group row text-danger">
                        <label class="col-sm-2 col-form-label" for="plastico">Plástico:</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control text-danger" id="plastico" name="plastico">
                        </div>
                    </div>
                    <div class="form-group row text-warning">
                        <label class="col-sm-2 col-form-label" for="metal">Metal:</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control text-warning" id="metal" name="metal">
                        </div>
                    </div>
                    <div class="form-group row text-primary">
                        <label class="col-sm-2 col-form-label" for="papel">Papel:</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control text-primary" id="papel" name="papel">
                        </div>
                    </div>
                    <div class="form-group row text-success">
                        <label class="col-sm-2 col-form-label" for="vidro">Vidro:</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control text-success" id="vidro" name="vidro">
                        </div>
                    </div>
                    <div class="form-group row text-dark">
                        <label class="col-sm-2 col-form-label" for="oleo">Óleo:</label>
                        <div class="col-sm-10">
                            <input type="text" class="form-control text-dark" id="oleo" name="oleo">
                        </div>
                    </div>
                </div>

                <div class="modal-footer">
                    <button type="reset" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn btn-primary">Gravar</button>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}
{% block js %}
<script>
$(document).ready(function () {
    $(document).off("click", ".insert-id");
    $(document).on("click", ".insert-id", function () {
        const id = $(this).data('id');
        $('#id_pontuacao').val(id);
    });
});
</script>
{% endblock %}