{% extends "base.phtml" %}

{% block content %}

<div class="container">
    <h2 class="display-4 text-center mb-4">Pontuação</h2>
    <div class="row">
        <div class="col">
            <div class="table-responsive">
                <table class="table table-striped table-borderless table-sm">
                    <thead class="thead-dark">
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Grupo</th>
                            <th scope="col">Usuário</th>
                            <th scope="col">Pontuação</th>
                            <th scope="col">Ação</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th scope="row">1</th>
                            <td>Grupo 1</td>
                            <td>José Alvares</td>
                            <td>
                                <span class="badge badge-danger" title="Plástico">9,80kg</span>
                                <span class="badge badge-warning" title="Metal">1,23kg</span>
                                <span class="badge badge-primary" title="Papel">5,00kg</span>
                                <span class="badge badge-success" title="Vidro">3,56kg</span>
                                <span class="badge badge-dark" title="Óleo">1,80L</span>
                            </td>
                            <td>
                                <a class="btn btn-sm btn-primary" href="#" role="button" data-toggle="modal"
                                    data-target="#insertPontuacao">
                                    <i class="fas fa-plus-circle"></i>
                                </a>
                            </td>
                        </tr>
                        <tr>
                            <th scope="row">2</th>
                            <td>Grupo 1</td>
                            <td>Sandra Ferreira</td>
                            <td>
                                <span class="badge badge-danger" title="Plástico">4,07kg</span>
                                <span class="badge badge-warning" title="Metal">7,10kg</span>
                                <span class="badge badge-primary" title="Papel">1,40kg</span>
                                <span class="badge badge-success" title="Vidro">1,92kg</span>
                                <span class="badge badge-dark" title="Óleo">2,40L</span>
                            </td>
                            <td>
                                <a class="btn btn-sm btn-primary" href="#" role="button" data-toggle="modal"
                                    data-target="#insertPontuacao">
                                    <i class="fas fa-plus-circle"></i>
                                </a>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="insertPontuacao" tabindex="-1" role="dialog" aria-labelledby="insertPontuacaoLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <form>
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <input type="hidden" name="id_pontuacao" value="" />
                    <div class="form-group row text-danger">
                        <label class="col-sm-2 col-form-label" for="plastico_pontuacao">Plástico:</label>
                        <div class="col-sm-10">
                            <input type="number" class="form-control text-danger" id="plastico_pontuacao"
                                name="plastico_pontuacao">
                        </div>
                    </div>
                    <div class="form-group row text-warning">
                        <label class="col-sm-2 col-form-label" for="metal_pontuacao">Metal:</label>
                        <div class="col-sm-10">
                            <input type="number" class="form-control text-warning" id="metal_pontuacao"
                                name="metal_pontuacao">
                        </div>
                    </div>
                    <div class="form-group row text-primary">
                        <label class="col-sm-2 col-form-label" for="papel_pontuacao">Papel:</label>
                        <div class="col-sm-10">
                            <input type="number" class="form-control text-primary" id="papel_pontuacao"
                                name="papel_pontuacao">
                        </div>
                    </div>
                    <div class="form-group row text-success">
                        <label class="col-sm-2 col-form-label" for="vidro_pontuacao">Vidro:</label>
                        <div class="col-sm-10">
                            <input type="number" class="form-control text-success" id="vidro_pontuacao"
                                name="vidro_pontuacao">
                        </div>
                    </div>
                    <div class="form-group row text-dark">
                        <label class="col-sm-2 col-form-label" for="oleo_pontuacao">Óleo:</label>
                        <div class="col-sm-10">
                            <input type="number" class="form-control text-dark" id="oleo_pontuacao"
                                name="oleo_pontuacao">
                        </div>
                    </div>
                </div>
              
  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                    <button type="submit" class="btn btn-primary">Gravar</button>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}