{% extends "base.phtml" %}

{% block content %}

{% for key, mensagem in mensagens %}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    <strong>{{ key }}</strong>
    {% for msg in mensagem %}
    {{ msg }}
    {% endfor %}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
{% endfor %}

<div class="container">
    <h2 class="display-4 text-center mb-4">Usuários</h2>
    <div class="row">
        <div class="col-sm-8">
            <div class="table-responsive">
                <table class="table table-striped table-borderless table-sm">
                    <thead class="thead-dark">
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">Nome</th>
                            <th scope="col">E-mail</th>
                            <th scope="col">Apto</th>
                            <th scope="col">Grupo</th>
                            <th scope="col">Ação</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for usuario in usuarios %}
                        <tr>
                            <th scope="row">{{ usuario.id }}</th>
                            <td>{{ usuario.nome }}</td>
                            <td>{{ usuario.email }}</td>
                            <td>{{ usuario.endereco }}</td>
                            <td>{{ usuario.grupo }}</td>
                            <td>
                                <a class="btn btn-sm btn-warning" href="{{ url }}usuarios/{{ usuario.id }}" role="button">
                                    <i class="fas fa-edit"></i>
                                </a>
                                <button type="button" class="btn btn-sm btn-danger" onclick="deletar({{ usuario.id }})" role="button">
                                    <i class="fas fa-trash-alt"></i>
                                    </a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="col">
            <form method="post" action="{{ url }}usuarios/{{ usuario.id }}">
                <input type="hidden" name="id" value="{{ usuario.id }}" />
                <div class="form-group">
                    <label for="nome" class="sr-only">Nome:</label>
                    <input type="text" class="form-control" id="nome" name="nome" aria-describedby="nomeHelp" placeholder="Nome" value="{{ usuario.nome }}">
                    <small id="nomeHelp" class="form-text text-muted">Nome do usuário.</small>
                </div>
                <div class="form-group">
                    <label for="email" class="sr-only">E-mail:</label>
                    <input type="email" class="form-control" id="email" name="email" aria-describedby="emailHelp" placeholder="E-mail" value="{{ usuario.email }}">
                    <small id="emailHelp" class="form-text text-muted">E-mail do usuário.</small>
                </div>
                <div class="form-group">
                    <label for="endereco" class="sr-only">Nome:</label>
                    <input type="text" class="form-control" id="endereco" name="endereco" aria-describedby="aptoHelp" placeholder="Apto" value="{{ usuario.nome }}">
                    <small id="aptoHelp" class="form-text text-muted">Apartamento do usuário.</small>
                </div>
                <div class="form-group">
                    <label for="cd_grupo" class="sr-only">Grupo:</label>
                    <select class="custom-select" name="cd_grupo" id="cd_grupo">
                        <option>-</option>
                        {% for grupo in grupos %}
                        <option value="{{ grupo.id }}" {% if grupo.id == usuario.cd_grupo %} selected {% endif %}>{{ grupo.nome }}</option>
                        {% endfor %}

                    </select>
                    <small id="aptoHelp" class="form-text text-muted">Apartamento do usuário.</small>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Gravar</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block js %}
<script>
    const deletar = function(id) {
        const swalWithBootstrapButtons = Swal.mixin({
            customClass: {
                confirmButton: 'btn btn-success',
                cancelButton: 'btn btn-danger'
            },
            buttonsStyling: false
        });
        swalWithBootstrapButtons.fire({
            title: 'Apagar?',
            text: "Esta ação irá apagar este registro!",
            type: 'warning',
            showCancelButton: true,
            confirmButtonText: 'Sim, apague!',
            cancelButtonText: 'Não, cancele!',
            reverseButtons: true
        }).then((result) => {
            if (result.value) {
                $.post($('#base_url').val() + 'usuarios/' + id + '/del', function(data) {
                    swalWithBootstrapButtons.fire('Apagado!', 'O registro foi apagado.', 'success');
                    location.reload();
                });
            } else if (result.dismiss === Swal.DismissReason.cancel) {
                swalWithBootstrapButtons.fire('Cancelado', 'O registro foi preservado :)', 'error');
            }
        });
    }
</script>
{% endblock %}
